### ISSUE TITLE
Record Video

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/empirica-videocall#2]
As a scientist, I want to record the video from deliberation experiments for later analysis so that I might understand how particular interventions produce different deliberation outcomes.

As an experiment manager, I need to make sure these videos are stored securely over the long term, with minimal ongoing maintenance, so that I can ensure confidentiality for participants and fulfill my IRB expectations.

We need a solution for streaming video from jitsi to secure long-term storage. 

The IRB-approved deliberation procedure includes these statements on video storage:
> - Discussions will take place online via video, audio, or text chat. Discussions will be recorded for post-hoc analysis, with participant consent, and recordings will be stored anonymously and securely.
> - Video files will be managed on a secure server and access privileges will be granted individually to researchers who agree to maintain their confidentiality, as necessary for analysis.
> - All data, including video data, will be collected automatically and will be automatically stored on a secure server with restricted access permissions. Video data will be stored separately from other forms of data, and access permissions will be managed separately from other forms of behavioral or survey data. We will maintain copies of the data we use indefinitely. Non-sensitive data will be stored in a private, secure database attached to the experiment platform. Periodically, anonymous data about participant behavior and survey results will be released in a public format (e.g. via Github). Participants will consent to this use of data prior to participation.
> - Video recordings will be kept on a separate, encrypted, password-protected server from other research data, and linked only with randomly generated identifiers. Video recordings may be shared on an individual basis with outside researchers under written agreement to preserve the security and confidentiality of the recordings.

## Notes:
- Dropbox is apparently compatible with Jitsi: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web-integrations#creating-the-dropbox-app-for-dropbox-recording-integration
- Jitsi is open-source, and so we may be able to integrate another solution.
- This is the sort of thing that [Panopto](https://www.panopto.com/) was designed for, if we can integrate it with Jitsi.
- It would be slick if we could stream a different audio channel for each individual, to make automatic parsing and analysis easy. This could also be a capability for future development.

## Ready to close when:
- [ ] Video streams automatically to the storage solution when participants enter a room
- [ ] Video files are tagged with the date, `gameid` and `stageid` from empirica.
- [ ] URLs to the video files are saved with empirica data (if this is possible)
- [ ] Videos are only visible to authorized viewers.

**Comment by JamesPHoughton** [comment]
@Alan-Qiao trying to run jibri (the recording component) in a local container.

**Comment by Alan-Qiao** [comment]
Update: Decided to move away from Jitsi/Jibri due to impracticality of recording multiple sessions concurrently.
Now working on Eyeson solution.

**Comment by Alan-Qiao** [comment]
Compare eyeson and eyeson-node packages to see which one works better.
eyeson seems more customizable and more recently updated, but misses some crucial components of the API (create a meeting).
eyeson-node more straightforward integration of api, but seems to not support component video.

**Comment by Alan-Qiao** [comment]
Decided on using eyeson package to maintain client connection and event handling. (Maximize customizability).
Directly communicate with eyeson API through fetch requests for API features not implemented in eyeson package.

BUG: Test run with CURL yielded recording download link, but received "access denied" message in attempt to access recording
